// Auto-generated practice word list (offline). Source: /api/words.
// Balinese is computed on-device by converter.dart.
const List<Map<String, String?>> kWords = [
  {"latin": "bali", "meaning": "Bali (pulau)", "category": "Tempat", "difficulty": "easy"},
  {"latin": "dewa", "meaning": "dewa / deity", "category": "Agama", "difficulty": "easy"},
  {"latin": "pura", "meaning": "pura / temple", "category": "Agama", "difficulty": "easy"},
  {"latin": "api", "meaning": "api / fire", "category": "Alam", "difficulty": "easy"},
  {"latin": "suka", "meaning": "suka / happy", "category": "Umum", "difficulty": "easy"},
  {"latin": "duka", "meaning": "duka / sadness", "category": "Umum", "difficulty": "easy"},
  {"latin": "jaya", "meaning": "jaya / victory", "category": "Umum", "difficulty": "easy"},
  {"latin": "kuta", "meaning": "Kuta (tempat)", "category": "Tempat", "difficulty": "easy"},
  {"latin": "padi", "meaning": "padi / rice plant", "category": "Alam", "difficulty": "easy"},
  {"latin": "toya", "meaning": "toya / water (formal)", "category": "Alam", "difficulty": "easy"},
  {"latin": "sapi", "meaning": "sapi / cow", "category": "Hewan", "difficulty": "easy"},
  {"latin": "kuda", "meaning": "kuda / horse", "category": "Hewan", "difficulty": "easy"},
  {"latin": "nasi", "meaning": "nasi / cooked rice", "category": "Makanan", "difficulty": "easy"},
  {"latin": "babi", "meaning": "babi / pig", "category": "Hewan", "difficulty": "easy"},
  {"latin": "raja", "meaning": "raja / king", "category": "Umum", "difficulty": "easy"},
  {"latin": "dadi", "meaning": "dadi / to become", "category": "Umum", "difficulty": "easy"},
  {"latin": "malu", "meaning": "malu / first / ahead", "category": "Umum", "difficulty": "easy"},
  {"latin": "tua", "meaning": "tua / old", "category": "Umum", "difficulty": "easy"},
  {"latin": "muda", "meaning": "muda / young", "category": "Umum", "difficulty": "easy"},
  {"latin": "gede", "meaning": "gede / big", "category": "Umum", "difficulty": "easy"},
  {"latin": "ubud", "meaning": "Ubud (tempat)", "category": "Tempat", "difficulty": "medium"},
  {"latin": "surya", "meaning": "surya / matahari", "category": "Alam", "difficulty": "medium"},
  {"latin": "candra", "meaning": "candra / bulan", "category": "Alam", "difficulty": "medium"},
  {"latin": "banyu", "meaning": "banyu / air", "category": "Alam", "difficulty": "medium"},
  {"latin": "angin", "meaning": "angin / wind", "category": "Alam", "difficulty": "medium"},
  {"latin": "barong", "meaning": "barong / pelindung", "category": "Budaya", "difficulty": "medium"},
  {"latin": "wayang", "meaning": "wayang / shadow puppet", "category": "Budaya", "difficulty": "medium"},
  {"latin": "gamelan", "meaning": "gamelan / musik tradisional", "category": "Budaya", "difficulty": "medium"},
  {"latin": "kecak", "meaning": "kecak / tari kecak", "category": "Budaya", "difficulty": "medium"},
  {"latin": "legong", "meaning": "legong / tarian Bali", "category": "Budaya", "difficulty": "medium"},
  {"latin": "canang", "meaning": "canang / sesajen bunga", "category": "Agama", "difficulty": "medium"},
  {"latin": "tirta", "meaning": "tirta / air suci", "category": "Agama", "difficulty": "medium"},
  {"latin": "banten", "meaning": "banten / sesajen", "category": "Agama", "difficulty": "medium"},
  {"latin": "subak", "meaning": "subak / sistem irigasi", "category": "Budaya", "difficulty": "medium"},
  {"latin": "banjar", "meaning": "banjar / komunitas desa", "category": "Budaya", "difficulty": "medium"},
  {"latin": "jaba", "meaning": "jaba / halaman luar pura", "category": "Agama", "difficulty": "medium"},
  {"latin": "jeroan", "meaning": "jeroan / dalam pura", "category": "Agama", "difficulty": "medium"},
  {"latin": "galungan", "meaning": "galungan / hari raya", "category": "Agama", "difficulty": "medium"},
  {"latin": "kuningan", "meaning": "kuningan / hari raya", "category": "Agama", "difficulty": "medium"},
  {"latin": "nyepi", "meaning": "nyepi / hari raya sunyi", "category": "Agama", "difficulty": "medium"},
  {"latin": "dharma", "meaning": "dharma / kewajiban", "category": "Filosofi", "difficulty": "hard"},
  {"latin": "karma", "meaning": "karma / perbuatan", "category": "Filosofi", "difficulty": "hard"},
  {"latin": "mantra", "meaning": "mantra / doa sakral", "category": "Agama", "difficulty": "hard"},
  {"latin": "yoga", "meaning": "yoga / latihan spiritual", "category": "Filosofi", "difficulty": "hard"},
  {"latin": "moksha", "meaning": "moksha / pembebasan jiwa", "category": "Filosofi", "difficulty": "hard"},
  {"latin": "samsara", "meaning": "samsara / siklus kehidupan", "category": "Filosofi", "difficulty": "hard"},
  {"latin": "brahma", "meaning": "Brahma / dewa pencipta", "category": "Agama", "difficulty": "hard"},
  {"latin": "wisnu", "meaning": "Wisnu / dewa pemelihara", "category": "Agama", "difficulty": "hard"},
  {"latin": "shiwa", "meaning": "Shiwa / dewa penghancur", "category": "Agama", "difficulty": "hard"},
  {"latin": "saraswati", "meaning": "Saraswati / dewi ilmu", "category": "Agama", "difficulty": "hard"},
  {"latin": "lakshmi", "meaning": "Lakshmi / dewi kemakmuran", "category": "Agama", "difficulty": "hard"},
  {"latin": "ramayana", "meaning": "Ramayana / epos Hindu", "category": "Sastra", "difficulty": "hard"},
  {"latin": "mahabharata", "meaning": "Mahabharata / epos Hindu", "category": "Sastra", "difficulty": "hard"},
  {"latin": "kakawin", "meaning": "kakawin / puisi Jawa Kuno", "category": "Sastra", "difficulty": "hard"},
  {"latin": "lontar", "meaning": "lontar / daun palem untuk menulis", "category": "Budaya", "difficulty": "hard"},
];
