// Auto-generated practice word list (offline). Source: /api/words.
// Balinese is computed on-device by converter.dart.
const List<Map<String, String?>> kWords = [
  {"latin": "bali", "meaning": "Bali (pulau)", "category": "Tempat", "difficulty": "easy"},
  {"latin": "dewa", "meaning": "dewa / deity", "category": "Agama", "difficulty": "easy"},
  {"latin": "pura", "meaning": "pura / temple", "category": "Agama", "difficulty": "easy"},
  {"latin": "api", "meaning": "api / fire", "category": "Alam", "difficulty": "easy"},
  {"latin": "suka", "meaning": "suka / happy", "category": "Umum", "difficulty": "easy"},
  {"latin": "duka", "meaning": "duka / sadness", "category": "Umum", "difficulty": "easy"},
  {"latin": "jaya", "meaning": "jaya / victory", "category": "Umum", "difficulty": "easy"},
  {"latin": "kuta", "meaning": "Kuta (tempat)", "category": "Tempat", "difficulty": "easy"},
  {"latin": "padi", "meaning": "padi / rice plant", "category": "Alam", "difficulty": "easy"},
  {"latin": "toya", "meaning": "toya / water (formal)", "category": "Alam", "difficulty": "easy"},
  {"latin": "sapi", "meaning": "sapi / cow", "category": "Hewan", "difficulty": "easy"},
  {"latin": "kuda", "meaning": "kuda / horse", "category": "Hewan", "difficulty": "easy"},
  {"latin": "nasi", "meaning": "nasi / cooked rice", "category": "Makanan", "difficulty": "easy"},
  {"latin": "babi", "meaning": "babi / pig", "category": "Hewan", "difficulty": "easy"},
  {"latin": "raja", "meaning": "raja / king", "category": "Umum", "difficulty": "easy"},
  {"latin": "dadi", "meaning": "dadi / to become", "category": "Umum", "difficulty": "easy"},
  {"latin": "malu", "meaning": "malu / first / ahead", "category": "Umum", "difficulty": "easy"},
  {"latin": "tua", "meaning": "tua / old", "category": "Umum", "difficulty": "easy"},
  {"latin": "muda", "meaning": "muda / young", "category": "Umum", "difficulty": "easy"},
  {"latin": "gede", "meaning": "gede / big", "category": "Umum", "difficulty": "easy"},
  {"latin": "ubud", "meaning": "Ubud (tempat)", "category": "Tempat", "difficulty": "medium"},
  {"latin": "surya", "meaning": "surya / matahari", "category": "Alam", "difficulty": "medium"},
  {"latin": "candra", "meaning": "candra / bulan", "category": "Alam", "difficulty": "medium"},
  {"latin": "banyu", "meaning": "banyu / air", "category": "Alam", "difficulty": "medium"},
  {"latin": "angin", "meaning": "angin / wind", "category": "Alam", "difficulty": "medium"},
  {"latin": "barong", "meaning": "barong / pelindung", "category": "Budaya", "difficulty": "medium"},
  {"latin": "wayang", "meaning": "wayang / shadow puppet", "category": "Budaya", "difficulty": "medium"},
  {"latin": "gamelan", "meaning": "gamelan / musik tradisional", "category": "Budaya", "difficulty": "medium"},
  {"latin": "kecak", "meaning": "kecak / tari kecak", "category": "Budaya", "difficulty": "medium"},
  {"latin": "legong", "meaning": "legong / tarian Bali", "category": "Budaya", "difficulty": "medium"},
  {"latin": "canang", "meaning": "canang / sesajen bunga", "category": "Agama", "difficulty": "medium"},
  {"latin": "tirta", "meaning": "tirta / air suci", "category": "Agama", "difficulty": "medium"},
  {"latin": "banten", "meaning": "banten / sesajen", "category": "Agama", "difficulty": "medium"},
  {"latin": "subak", "meaning": "subak / sistem irigasi", "category": "Budaya", "difficulty": "medium"},
  {"latin": "banjar", "meaning": "banjar / komunitas desa", "category": "Budaya", "difficulty": "medium"},
  {"latin": "jaba", "meaning": "jaba / halaman luar pura", "category": "Agama", "difficulty": "medium"},
  {"latin": "jeroan", "meaning": "jeroan / dalam pura", "category": "Agama", "difficulty": "medium"},
  {"latin": "galungan", "meaning": "galungan / hari raya", "category": "Agama", "difficulty": "medium"},
  {"latin": "kuningan", "meaning": "kuningan / hari raya", "category": "Agama", "difficulty": "medium"},
  {"latin": "nyepi", "meaning": "nyepi / hari raya sunyi", "category": "Agama", "difficulty": "medium"},
  {"latin": "dharma", "meaning": "dharma / kewajiban", "category": "Filosofi", "difficulty": "hard"},
  {"latin": "karma", "meaning": "karma / perbuatan", "category": "Filosofi", "difficulty": "hard"},
  {"latin": "mantra", "meaning": "mantra / doa sakral", "category": "Agama", "difficulty": "hard"},
  {"latin": "yoga", "meaning": "yoga / latihan spiritual", "category": "Filosofi", "difficulty": "hard"},
  {"latin": "moksha", "meaning": "moksha / pembebasan jiwa", "category": "Filosofi", "difficulty": "hard"},
  {"latin": "samsara", "meaning": "samsara / siklus kehidupan", "category": "Filosofi", "difficulty": "hard"},
  {"latin": "brahma", "meaning": "Brahma / dewa pencipta", "category": "Agama", "difficulty": "hard"},
  {"latin": "wisnu", "meaning": "Wisnu / dewa pemelihara", "category": "Agama", "difficulty": "hard"},
  {"latin": "shiwa", "meaning": "Shiwa / dewa penghancur", "category": "Agama", "difficulty": "hard"},
  {"latin": "saraswati", "meaning": "Saraswati / dewi ilmu", "category": "Agama", "difficulty": "hard"},
  {"latin": "lakshmi", "meaning": "Lakshmi / dewi kemakmuran", "category": "Agama", "difficulty": "hard"},
  {"latin": "ramayana", "meaning": "Ramayana / epos Hindu", "category": "Sastra", "difficulty": "hard"},
  {"latin": "mahabharata", "meaning": "Mahabharata / epos Hindu", "category": "Sastra", "difficulty": "hard"},
  {"latin": "kakawin", "meaning": "kakawin / puisi Jawa Kuno", "category": "Sastra", "difficulty": "hard"},
  {"latin": "lontar", "meaning": "lontar / daun palem untuk menulis", "category": "Budaya", "difficulty": "hard"},
  {"latin": "bapa", "meaning": "bapa / ayah", "category": "Keluarga", "difficulty": "easy"},
  {"latin": "meme", "meaning": "meme / ibu", "category": "Keluarga", "difficulty": "easy"},
  {"latin": "pianak", "meaning": "pianak / anak", "category": "Keluarga", "difficulty": "easy"},
  {"latin": "nyama", "meaning": "nyama / saudara", "category": "Keluarga", "difficulty": "easy"},
  {"latin": "mata", "meaning": "mata / eye", "category": "Tubuh", "difficulty": "easy"},
  {"latin": "lima", "meaning": "lima / tangan", "category": "Tubuh", "difficulty": "easy"},
  {"latin": "batis", "meaning": "batis / kaki", "category": "Tubuh", "difficulty": "easy"},
  {"latin": "sirah", "meaning": "sirah / kepala", "category": "Tubuh", "difficulty": "easy"},
  {"latin": "biu", "meaning": "biu / pisang", "category": "Makanan", "difficulty": "easy"},
  {"latin": "nyuh", "meaning": "nyuh / kelapa", "category": "Makanan", "difficulty": "easy"},
  {"latin": "taluh", "meaning": "taluh / telur", "category": "Makanan", "difficulty": "easy"},
  {"latin": "bulan", "meaning": "bulan / moon", "category": "Alam", "difficulty": "easy"},
  {"latin": "gunung", "meaning": "gunung / mountain", "category": "Alam", "difficulty": "easy"},
  {"latin": "pasih", "meaning": "pasih / laut", "category": "Alam", "difficulty": "easy"},
  {"latin": "umah", "meaning": "umah / rumah", "category": "Tempat", "difficulty": "easy"},
  {"latin": "semengan", "meaning": "semengan / pagi", "category": "Waktu", "difficulty": "medium"},
  {"latin": "peteng", "meaning": "peteng / malam", "category": "Waktu", "difficulty": "medium"},
  {"latin": "majalan", "meaning": "majalan / berjalan", "category": "Kata kerja", "difficulty": "medium"},
  {"latin": "madaar", "meaning": "madaar / makan", "category": "Kata kerja", "difficulty": "medium"},
  {"latin": "magae", "meaning": "magae / bekerja", "category": "Kata kerja", "difficulty": "medium"},
  {"latin": "melajah", "meaning": "melajah / belajar", "category": "Kata kerja", "difficulty": "medium"},
  {"latin": "jegeg", "meaning": "jegeg / cantik", "category": "Sifat", "difficulty": "medium"},
  {"latin": "bagus", "meaning": "bagus / tampan", "category": "Sifat", "difficulty": "medium"},
  {"latin": "cerik", "meaning": "cerik / kecil", "category": "Sifat", "difficulty": "medium"},
  {"latin": "bareng", "meaning": "bareng / bersama", "category": "Umum", "difficulty": "medium"},
  {"latin": "catur", "meaning": "catur / empat", "category": "Angka", "difficulty": "hard"},
  {"latin": "aksara", "meaning": "aksara / huruf", "category": "Sastra", "difficulty": "hard"},
  {"latin": "ngaben", "meaning": "ngaben / upacara kremasi", "category": "Agama", "difficulty": "hard"},
  {"latin": "melasti", "meaning": "melasti / upacara penyucian", "category": "Agama", "difficulty": "hard"},
  {"latin": "odalan", "meaning": "odalan / hari jadi pura", "category": "Agama", "difficulty": "hard"},
  {"latin": "pemangku", "meaning": "pemangku / pemimpin upacara", "category": "Agama", "difficulty": "hard"},
  {"latin": "sekala", "meaning": "sekala / dunia nyata", "category": "Filosofi", "difficulty": "hard"},
  {"latin": "niskala", "meaning": "niskala / dunia gaib", "category": "Filosofi", "difficulty": "hard"},
  {"latin": "celeng", "meaning": "celeng / babi", "category": "Hewan", "difficulty": "easy"},
  {"latin": "cicing", "meaning": "cicing / anjing", "category": "Hewan", "difficulty": "easy"},
  {"latin": "meong", "meaning": "meong / kucing", "category": "Hewan", "difficulty": "easy"},
  {"latin": "jaran", "meaning": "jaran / kuda", "category": "Hewan", "difficulty": "easy"},
  {"latin": "bikul", "meaning": "bikul / tikus", "category": "Hewan", "difficulty": "easy"},
  {"latin": "jukut", "meaning": "jukut / sayur", "category": "Makanan", "difficulty": "easy"},
  {"latin": "kopi", "meaning": "kopi / coffee", "category": "Makanan", "difficulty": "easy"},
  {"latin": "gula", "meaning": "gula / sugar", "category": "Makanan", "difficulty": "easy"},
  {"latin": "uyah", "meaning": "uyah / garam", "category": "Makanan", "difficulty": "easy"},
  {"latin": "langit", "meaning": "langit / sky", "category": "Alam", "difficulty": "easy"},
  {"latin": "tanah", "meaning": "tanah / soil", "category": "Alam", "difficulty": "easy"},
  {"latin": "batu", "meaning": "batu / stone", "category": "Alam", "difficulty": "easy"},
  {"latin": "kayu", "meaning": "kayu / wood", "category": "Alam", "difficulty": "easy"},
  {"latin": "desa", "meaning": "desa / village", "category": "Tempat", "difficulty": "easy"},
  {"latin": "pasar", "meaning": "pasar / market", "category": "Tempat", "difficulty": "easy"},
  {"latin": "bunga", "meaning": "bunga / kembang", "category": "Alam", "difficulty": "medium"},
  {"latin": "carik", "meaning": "carik / sawah", "category": "Tempat", "difficulty": "medium"},
  {"latin": "semeton", "meaning": "semeton / kerabat", "category": "Keluarga", "difficulty": "medium"},
  {"latin": "rerama", "meaning": "rerama / orang tua", "category": "Keluarga", "difficulty": "medium"},
  {"latin": "kurenan", "meaning": "kurenan / pasangan", "category": "Keluarga", "difficulty": "medium"},
  {"latin": "megending", "meaning": "megending / bernyanyi", "category": "Kata kerja", "difficulty": "medium"},
  {"latin": "ngigel", "meaning": "ngigel / menari", "category": "Kata kerja", "difficulty": "medium"},
  {"latin": "masare", "meaning": "masare / tidur", "category": "Kata kerja", "difficulty": "medium"},
  {"latin": "mabalih", "meaning": "mabalih / menonton", "category": "Kata kerja", "difficulty": "medium"},
  {"latin": "demen", "meaning": "demen / senang", "category": "Sifat", "difficulty": "medium"},
  {"latin": "sebet", "meaning": "sebet / sedih", "category": "Sifat", "difficulty": "medium"},
  {"latin": "gelis", "meaning": "gelis / cepat", "category": "Sifat", "difficulty": "medium"},
  {"latin": "adeng", "meaning": "adeng / lambat", "category": "Sifat", "difficulty": "medium"},
  {"latin": "becik", "meaning": "becik / baik", "category": "Sifat", "difficulty": "medium"},
  {"latin": "corah", "meaning": "corah / buruk", "category": "Sifat", "difficulty": "medium"},
  {"latin": "swadharma", "meaning": "swadharma / kewajiban", "category": "Filosofi", "difficulty": "hard"},
  {"latin": "tatwa", "meaning": "tatwa / filsafat", "category": "Filosofi", "difficulty": "hard"},
  {"latin": "susila", "meaning": "susila / etika", "category": "Filosofi", "difficulty": "hard"},
  {"latin": "upakara", "meaning": "upakara / sarana upacara", "category": "Agama", "difficulty": "hard"},
  {"latin": "yadnya", "meaning": "yadnya / korban suci", "category": "Agama", "difficulty": "hard"},
  {"latin": "pawiwahan", "meaning": "pawiwahan / pernikahan", "category": "Agama", "difficulty": "hard"},
  {"latin": "pratima", "meaning": "pratima / arca suci", "category": "Agama", "difficulty": "hard"},
  {"latin": "sasih", "meaning": "sasih / bulan kalender", "category": "Waktu", "difficulty": "hard"},
  {"latin": "penjor", "meaning": "penjor / hiasan bambu", "category": "Budaya", "difficulty": "hard"},
  {"latin": "ogoh", "meaning": "ogoh / ogoh-ogoh", "category": "Budaya", "difficulty": "hard"},
  {"latin": "yeh", "meaning": "yeh / air", "category": "Alam", "difficulty": "easy"},
  {"latin": "don", "meaning": "don / daun", "category": "Alam", "difficulty": "easy"},
  {"latin": "siap", "meaning": "siap / ayam", "category": "Hewan", "difficulty": "easy"},
  {"latin": "bebek", "meaning": "bebek / itik", "category": "Hewan", "difficulty": "easy"},
  {"latin": "roti", "meaning": "roti / bread", "category": "Makanan", "difficulty": "easy"},
  {"latin": "putih", "meaning": "putih / white", "category": "Warna", "difficulty": "easy"},
  {"latin": "barak", "meaning": "barak / merah", "category": "Warna", "difficulty": "easy"},
  {"latin": "selem", "meaning": "selem / hitam", "category": "Warna", "difficulty": "easy"},
  {"latin": "kuning", "meaning": "kuning / yellow", "category": "Warna", "difficulty": "easy"},
  {"latin": "gadang", "meaning": "gadang / hijau", "category": "Warna", "difficulty": "easy"},
  {"latin": "kuping", "meaning": "kuping / telinga", "category": "Tubuh", "difficulty": "easy"},
  {"latin": "untu", "meaning": "untu / gigi", "category": "Tubuh", "difficulty": "easy"},
  {"latin": "cangkem", "meaning": "cangkem / mulut", "category": "Tubuh", "difficulty": "medium"},
  {"latin": "besik", "meaning": "besik / satu", "category": "Angka", "difficulty": "easy"},
  {"latin": "dasa", "meaning": "dasa / sepuluh", "category": "Angka", "difficulty": "medium"},
  {"latin": "sanur", "meaning": "Sanur (tempat)", "category": "Tempat", "difficulty": "medium"},
  {"latin": "denpasar", "meaning": "Denpasar (kota)", "category": "Tempat", "difficulty": "medium"},
  {"latin": "singaraja", "meaning": "Singaraja (kota)", "category": "Tempat", "difficulty": "medium"},
  {"latin": "bedugul", "meaning": "Bedugul (tempat)", "category": "Tempat", "difficulty": "medium"},
  {"latin": "dina", "meaning": "dina / hari", "category": "Waktu", "difficulty": "medium"},
  {"latin": "sanja", "meaning": "sanja / sore", "category": "Waktu", "difficulty": "medium"},
  {"latin": "nginem", "meaning": "nginem / minum", "category": "Kata kerja", "difficulty": "medium"},
  {"latin": "ningeh", "meaning": "ningeh / mendengar", "category": "Kata kerja", "difficulty": "medium"},
  {"latin": "matakon", "meaning": "matakon / bertanya", "category": "Kata kerja", "difficulty": "medium"},
  {"latin": "numbas", "meaning": "numbas / membeli", "category": "Kata kerja", "difficulty": "medium"},
  {"latin": "wanen", "meaning": "wanen / berani", "category": "Sifat", "difficulty": "medium"},
  {"latin": "jujur", "meaning": "jujur / honest", "category": "Sifat", "difficulty": "medium"},
  {"latin": "rindik", "meaning": "rindik / musik bambu", "category": "Budaya", "difficulty": "medium"},
  {"latin": "suling", "meaning": "suling / seruling", "category": "Budaya", "difficulty": "medium"},
  {"latin": "topeng", "meaning": "topeng / mask", "category": "Budaya", "difficulty": "medium"},
  {"latin": "rejang", "meaning": "rejang / tarian sakral", "category": "Budaya", "difficulty": "hard"},
  {"latin": "tumpek", "meaning": "tumpek / hari otonan", "category": "Agama", "difficulty": "hard"},
  {"latin": "pagerwesi", "meaning": "pagerwesi / hari raya", "category": "Agama", "difficulty": "hard"},
  {"latin": "siwaratri", "meaning": "siwaratri / malam Siwa", "category": "Agama", "difficulty": "hard"},
  {"latin": "melukat", "meaning": "melukat / ritual penyucian", "category": "Agama", "difficulty": "hard"},
  {"latin": "trimurti", "meaning": "trimurti / tiga dewa utama", "category": "Filosofi", "difficulty": "hard"},
  {"latin": "atman", "meaning": "atman / jiwa", "category": "Filosofi", "difficulty": "hard"},
  {"latin": "pralaya", "meaning": "pralaya / kehancuran alam", "category": "Filosofi", "difficulty": "hard"},
  {"latin": "wariga", "meaning": "wariga / ilmu kalender Bali", "category": "Sastra", "difficulty": "hard"},
];
